### ISSUE TITLE
Segfault and "futex facility" error when attempting to run electron-mocha via GitHub actions, on Ubuntu only

### ISSUE THREAD

**Issue by Duckwhale** [jprichardson/electron-mocha#186]
Greetings!

I just started using ``electron-mocha`` in my Electron-based app. After setting up GitHub actions to run it automatically, the Ubuntu VM fails with a segfault. It works locally on my Linux Mint (Ubuntu-based) system however.

I tried changing the image to ``ubuntu-18.04``, limiting the workflow to just one thread, and installing ``electron-mocha`` globally instead of running it via ``npm``.

The latter gives me another weird error:

> The futex facility returned an unexpected error code./home/runner/work/_temp/e40c107f-666f-42bb-b0f1-5f2c48ca0e2e.sh: line 1:  2854 Aborted                 (core dumped) electron-mocha Tests/

This also only happens on the Ubuntu VM. Any idea what might be the problem, and more importantly how I can debug and fix it?

Thank you for your time!

**Comment by inukshuk** [comment]
I haven't seen this before.

I'd start with a minimal setup: a single passing test and run it with both `electron-mocha` and `electron-mocha --renderer`. If you can't reproduce it that way, I'd start reconstructing the environment you use for testing to get a better idea what's causing it.

**Comment by Duckwhale** [comment]
I managed to resolve the issue. Here's a short summary in case someone else encounters the same problem:

* It's caused by ``electron`` and not ``electron-mocha``
* Apparently, the Ubuntu runners provided by GitHub are unable to display electron's CLI output (terminal issue?)
* This means that merely running the electron executable fails with a ``SIGSEGV`` error
* Googling the seemingly-unrelated "futex error" lead to some issues in the electron repo that provided a workaround

What I ended up doing was prepending the ``npm test`` command run via the GitHub Action with this abomination:

> export DISPLAY=:45 && xvfb-run --server-num 45

The configuration (``test.yml``) for the GitHub action I modified as follows:

1. Adding the prefix string for Ubuntu only

```
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: windows-latest
            ubuntu-workaround-prefix-string: ''
          - os: macos-latest
            ubuntu-workaround-prefix-string: ''
          - os: ubuntu-latest
            ubuntu-workaround-prefix-string: export DISPLAY=:45 && xvfb-run --server-num 45
```

2. Inserting the awful thing before the test command


```
      - name: Run automated tests
        run: ${{ matrix.ubuntu-workaround-prefix-string }} npm test 
```

The workflow will then run tests normally on Windows and Mac, and use the xserver workaround on Ubuntu. Locally I can just use ``npm test`` on Linux also as my environment isn't as limited, so it's only for the CI.

I don't know *exactly* why it doesn't otherwise work on the VM, since I'm not primarily a Linux users and I don't care enough to research its terminal further at this time, but it doesn't really matter as long as it's working.
